version: '3.8'

services:
  app:
    build: .
    container_name: mkp_backend
    ports:
      - "127.0.0.1:8000:8080"
    environment:
      - DATABASE_URL=postgresql://mkp_user:mkp_password@db:5432/mkp_db
      - ALLOWED_ORIGINS=http://103.164.99.2,http://103.164.99.2:80,http://103.164.99.2:1101
    depends_on:
      - db
    restart: always
    networks:
      - mkp_network

  db:
    image: postgres:15
    container_name: mkp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mkp_user
      - POSTGRES_PASSWORD=mkp_password
      - POSTGRES_DB=mkp_db
    restart: always
    networks:
      - mkp_network

volumes:
  postgres_data:

networks:
  mkp_network:
    driver: bridge
